package com.lurregia.demo.model;

public enum ProdutoCartao {
    VISA_CLASSIC,
    VISA_ELECTRON,
    VISA_GOLD,
    VISA_PLATINUM,
    VISA_SIGNATURE,
    VISA_INFINITE,
    VISA_PURCHASING,
    VISA_PURCHASING_WITH_FLEET,
    VISA_CORPORATE_T_E,
    VISA_GOVERNMENT_CORPORATE_CREDIT,
    VISA_BUSINESS,
    VISA_SIGNATURE_BUSINESS,
    VISA_PLATINUM_BUSINESS,
    VISA_INFINITE_BUSINESS
}

