services:
  mqservices:
    image: ibmcom/mq:last
    hostaname: mq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
    ports:
      - "1414:1414"
      - "9443:9443"

  container_name: mqserver
  stdin-open: true
  tty: true
  restart: always
